FROM hub.zpf.com/library/golang:alpine AS builder

ENV GO111MODULE=on
ENV GOFLAGS="-mod=vendor"

ENV SOURCE=/src
ADD . ${SOURCE}
WORKDIR ${SOURCE}

FROM debian:buster
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    && sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y ca-certificates

ENV SOURCE=/src
ENV SERVICE=/service
WORKDIR ${SERVICE}

ARG TARGET_USER
RUN echo ${TARGET_USER}
COPY --from=builder ${SOURCE}/${TARGET_USER} .
COPY --from=builder ${SOURCE}/conf configs
RUN echo "/${SERVICE}/${TARGET_USER}" > /start.bash; \
    chmod +x /start.bash

CMD ["/bin/sh", "/start.bash"]